#spring:
#  application:
#    name: API-GATEWAY
#  cloud:
#    gateway:
##      discovery:
##        locator:
##          enabled: true
##          lower-case-service-id: true
#      routes:
#      - id: EMPLOYEE-SERVICE
#        uri: lb://EMPLOYEE-SERVICE
#        predicates:
#         - Path=/api/employees/v1/**
#      - id: DEPARTMENT-SERVICE
#        uri: lb://DEPARTMENT-SERVICE
#        predicates:
#         - Path=/api/departments/v1/**
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: http://localhost:3000
#            allowedMethods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
#
#  zipkin:
#    base-url: http://127.0.0.1:9411/
#
#server:
#    port: 9191
#
#eureka:
#  instance:
#    client:
#      serviceUrl:
#        defaultZone: http://localhost:8761/eureka/
#
#logging:
#  level:
#    org:
#      springframework:
#        cloud:
#          gateway:
#            handler:
#              RoutePredicateHandlerMapping: DEBUG

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: EMPLOYEE-SERVICE
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/api/employees/v1/**
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - GET
                - POST
              allowedHeaders: '*'
              maxAge: 30
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/api/departments/v1/**

  zipkin:
    base-url: http://127.0.0.1:9411/

server:
  port: 9191

eureka:
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org:
      springframework:
        cloud:
          gateway:
            handler:
              RoutePredicateHandlerMapping: DEBUG